[project]
name = "qctooling"
version = "0.1.0"
description = "Tooling to spare QC output files and functions to generate common derived values"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.1",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"