import pathlib, io
from functools import wraps, partial
import numpy as np
import numpy.typing as npt
from datetime import datetime
from typing import Callable, TypeVar, Union, ParamSpec, List
from .writerBase import WriterBase
from ..classes import Wfn, l2orb, Basis_grp, Xyz, elements

P = ParamSpec("P")
T = TypeVar("T")

def catch_errors(func: Callable[P, T]) -> Callable[P, Union[T, Exception]]:
    @wraps(func)
    def wrapper(*args: P.args, **kwargs: P.kwargs) -> Union[T, Exception]:
        try:
            return func(*args, **kwargs)
        except Exception as e:
            return e
    return wrapper

@catch_errors
def _write_Header(file: io.TextIOWrapper, title: str) -> None:
    file.write("[Molden Format]\n")
    file.write("[Title]\n")
    file.write(title + "\n")

@catch_errors
def _write_Atoms(file: io.TextIOWrapper, xyz: Xyz) -> None:
    file.write("[Atoms] AU\n")
    for idx, (e, (x,y,z)) in enumerate(zip(xyz.elements, xyz.coordinates), start=1):
        file.write(f"{e:<4} {idx:4d} {elements.index(e)+1:3d} {x:12.6f} {y:12.6f} {z:12.6f}\n")

@catch_errors
def _write_GTO(file: io.TextIOWrapper, basis: List[Basis_grp]) -> None:
    current_atom_idx = 0
    file.write("[GTO]")
    for b in basis:
        grp_atom_idx = b.atom_idx + 1
        if current_atom_idx < grp_atom_idx:
            file.write(f"\n    {grp_atom_idx} 0\n") #TODO: idk what the second number is supposed to be
            current_atom_idx = grp_atom_idx
        file.write(f"{l2orb[b.l]} {len(b.alpha):3d} 1.0\n")
        for alpha, coeff in zip(b.alpha, b.coeff):
            file.write(f" {alpha:15.8E} {coeff:15.8E}\n")
    file.write("\n[5D]\n[7F]\n[9G]\n") #TODO:Checkout if i might need to do more tagging

@catch_errors
def _write_MO(file:io.TextIOWrapper, irrep: npt.NDArray[np.str_], ener: npt.NDArray[np.float64],
              occ: npt.NDArray[np.float64], coeffs: npt.NDArray[np.float64]):
    file.write("[MO]\n")
    assert irrep.shape == ener.shape == occ.shape == coeffs.shape[:2], "uncompartible dimensions in wfn data"
    for i in range(irrep.shape[0]):
        if i == 0:
            spin = "Alpha"
        elif i == 1:
            spin = "Beta"
        else:
            raise ValueError("There should only be 2 different spin sets")
        
        for ir, e, o, cs in zip(irrep[i], ener[i], occ[i], coeffs[i]):
            file.write(f" Sym={ir:>16s}\n Ene={e:16.5f}\n Spin={spin:>15s}\n Occup={o:14.5f}\n")
            for j, c in enumerate(cs, start=1):
                file.write(f"{j:5d} {c:15.8E}\n")

#TODO: Pseudo handling
class MoldenWriter(WriterBase):
    wfn: Wfn

    def write(self) -> bool:
        with (self.path / (self.baseName + ".molden")).open("w") as f:

            for func in [
                partial(_write_Header, title=f"Generated by qctooling at {datetime.isoformat(datetime.now())}"),
                partial(_write_Atoms, xyz=self.wfn.xyz),
                partial(_write_GTO, basis=self.wfn.basis),
                partial(_write_MO, irrep=self.wfn.I, ener=self.wfn.E, occ=self.wfn.O, coeffs=self.wfn.C)
            ]:
                err = func(file=f)
                if err is not None:
                    self.logger.error(f"{func.func.__name__} failed: {err}")
                    return False
                else:
                    self.logger.info(f"{func.func.__name__} writing completed.")

        return True